apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onefacture.fullname" . }}-secret
  labels: {{- include "onefacture.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-dsn: {{ required "postgres.dsn is required" .Values.postgres.dsn | quote }}
  hash-pepper: {{ required "secrets.hashPepper is required" .Values.secrets.hashPepper | quote }}
  redis-password: {{ .Values.redis.password | quote }}
