{{- if .Values.observability.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "onefacture.fullname" . }}
  {{- with .Values.observability.serviceMonitor.namespace }}
  namespace: {{ . | quote }}
  {{- end }}
  labels:
    {{- include "onefacture.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "onefacture.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.observability.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout | quote }}
      path: {{ .Values.observability.serviceMonitor.path | quote }}
{{- end -}}
